name: demo workflow
on: workflow_dispatch
jobs:
  print_demo:
    runs-on: windows-latest
    steps:
      - name: print to consol
        run: echo Hello GH Action
      - name: print several lines
        run: |
          echo first line
          echo second line
        
